package com.example.greendao.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BILL".
 */
public class Bill {

    private Long id;
    private Integer userId;
    private Integer movieId;
    private String date;
    private String theaterName;
    private String movieName;
    private Integer price;
    private String ticketId;

    public Bill() {
    }

    public Bill(Long id) {
        this.id = id;
    }

    public Bill(Long id, Integer userId, Integer movieId, String date, String theaterName, String movieName, Integer price, String ticketId) {
        this.id = id;
        this.userId = userId;
        this.movieId = movieId;
        this.date = date;
        this.theaterName = theaterName;
        this.movieName = movieName;
        this.price = price;
        this.ticketId = ticketId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getMovieId() {
        return movieId;
    }

    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTheaterName() {
        return theaterName;
    }

    public void setTheaterName(String theaterName) {
        this.theaterName = theaterName;
    }

    public String getMovieName() {
        return movieName;
    }

    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }

    public Integer getPrice() {
        return price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public String getTicketId() {
        return ticketId;
    }

    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }

}
